### PR TITLE
For vendors: FAQ and Meet Your Market section

### LINKED ISSUE #495: [vendor page] Add new header image and link to contact us
The goal of this header is to provide an overview of the "story" of MobiMart for a vendor and to provide a clear CTA to contact us, via a button.

Screen Shot 2023-11-28 at 4 54 40 PM

### LINKED ISSUE #497: [vendor page] Add new Meet your market section
The "Meet your market" section is designed to give vendors a sense of the size and complexity of the CA market, and to direct them to the existing Provider Map via a button. 

Screen Shot 2023-11-28 at 4 51 13 PM

### PR DESCRIPTION
**Pull request by machikoyasuda**
closes #495 
closes #497

### CODE REVIEW

**Comment by machikoyasuda** [comment]
@thekaveman @angela-tran Ready for review.

I opted to just use the image for the statistics question. It would just have been way too hard to write a custom SVG.

**Comment by thekaveman** [comment]
@machikoyasuda I think this one still needs to be completed, yeah?

**Comment by machikoyasuda** [comment]
@thekaveman Yea this one will be ready for review tomorrow am.

**Comment by segacy1** [comment]
Stat here:

lg

**Comment by machikoyasuda** [comment]
@thekaveman This PR is now ready for review. Then, we'll have 1 last PR ready for review so we can merge For Vendors page to Prod.

**Review by thekaveman — APPROVED** [review]
LGTM!

**Pull request merged**
