### PR TITLE
Chore: Update Contracts landing with new intro text, FTA links

### LINKED ISSUE #418: Add copy to MobiMart pages that the RFP included all federal clauses
- Add the following copy to https://www.camobilitymarketplace.org/contracts/

- Add below first paragraph on the page, but above the GTFS blurb

**How do MSA’s Work?**

The Mobility Marketplace serves as Cal-ITP’s online catalog, where transit
providers can browse available goods and services and build a customized
transit technology system that suits their needs. The contracts or Master
Service Agreements (MSA) listed on this site are examples of a “state
purchasing schedule.” These schedules are agreements between a State or
related entity and a vendor(s) to provide goods or services at agreed upon
prices. Fundamentally, state purchasing schedules are designed to
accommodate other parties who may enter in and benefit from the
agreements in the future.

The Federal Transit Administration (FTA) [supports](https://www.transit.dot.gov/sites/fta.dot.gov/files/docs/Third%20Party%20Contracting%20Guidance%20%28Circular%204220.1F%29.pdf) recipients in pursuing state
purchasing schedules given that agreement parties have granted express
permission and all FTA and Federal requirements are met. More on Third Party
Procurement is available from the FTA [here](https://www.transit.dot.gov/funding/procurement/third-party-procurement/third-party-procurement-faqs).

### PR DESCRIPTION
**Pull request by thekaveman**
Closes #418

### CODE REVIEW

**Comment by thekaveman** [comment]
Netlify preview is available for review, see link above.

Note [my comment on the issue](https://github.com/cal-itp/mobility-marketplace/issues/418#issuecomment-1518318254), I updated the language around the links slightly. LMK if you want any changes here.

**Comment by thekaveman** [comment]
I'll merge this as-is by Sunday evening unless Erika has any other feedback.

**Review by esquared415 — CHANGES_REQUESTED** [review]
Hi @thekaveman & @mrose914! 

Marissa, I hear what you're saying about "State of CA contracts" possibly dissuading agencies from other states (although the EPAY payment processor contract is indeed just for CA agencies). So I'm suggesting some edits below that could help:

- [x] **Headline** // _Change to:_
California's Contracts—for U.S. transit agencies

- [x] **Contracts section** // _Change 1st sentence to:_
The State of California has Master Service Agreements (MSAs)—most of which are open to all public transportation providers in the U.S.—available to help you modernize your transit system. 

- [x] **Become GTFS-compliant first for best results** // _Tighten space between subhead and text block (please match styling on other sections of this page)._

- [ ] **Kegan's suggested edits to text links** // _Thank you for that reminder, Kegan! I love your fixes x2!_

Thanks, both!

**Comment by thekaveman** [comment]
> Become GTFS-compliant first for best results // *Tighten space between subhead and text block...*

Nice catch @esquared415 🙏 Thank you, fixed that and updated the content per your changes above.

**Pull request merged**
