### PR TITLE
For vendors: Add to nav

### LINKED ISSUE #500: [vendor page] Add link to Vendor page from top nav
Screen Shot 2023-11-28 at 4 39 16 PM

The new vendor page includes a requirement to add "For Vendors" as an option from the MobiMart homepage, specifically in the top nav. 

The rationale for this change is that vendors are a significant segment in terms of users of the site and should be able to quickly access information that may be most useful to them. 

**Acceptance Criteria:** 
After this change is implemented, the top nav should read, from left to right: 

- Products 
- Contracts
- For vendors 
- About 
- Contact us

### PR DESCRIPTION
**Pull request by machikoyasuda**
closes #500 

## What this PR does
- Adds one link to the nav
- Any CSS changes? No.

### CODE REVIEW

**Comment by machikoyasuda** [comment]
@thekaveman @angela-tran This is ready for review. Since we're going to be going live when all the PRs are in, this PR can be safely merged into the `499-for-vendors-newsletter` branch.

**Comment by angela-tran** [comment]
@machikoyasuda Do the design changes from https://github.com/cal-itp/mobility-marketplace/issues/500#issuecomment-1832186529 belong in this PR?

**Comment by angela-tran** [comment]
We currently don't get a preview site if the target branch is not `main`. A workaround for devs is to run the branch locally

**Comment by machikoyasuda** [comment]
@angela-tran No

**Comment by machikoyasuda** [comment]
@angela-tran the notes in that comment aren't actually changing anything / aren't actually reflected on Figma accurately:

- On Figma, some of the links have more spacing between them then others: 87 vs. 72
image
image
image

And having a hard-coded 72px number between links doesn't really make sense in a responsive web world.


- There are no styles for what the links on the Header look like on hover, and that hover style is what is setting the width of the link -- and _that's_ how the last link in the Header gets right-aligned with the main gutter: 
image
image

So until we have the Header's link styles, #501 and #502, we can't really change the nav. 

cc @segacy1

**Review by angela-tran — APPROVED** [review]

**Review by thekaveman — APPROVED** [review]
:world_map:

**Pull request merged**
