### PR TITLE
Refactor: update existing sections

### LINKED ISSUE #467: Homepage: Update existing copy / delete sections
## Hero / top section

- [ ] Update "Explore this site to find support..." copy
- [ ] Remove copy "Contracts update!"
- [ ] Remove copy "U.S. public transit providers, we have news for you..."
- [ ] Add View Contracts button in new style

## Lower sections
- [ ] Remove Map section and Modernize section
- [ ] Move up "What is Cal-ITP?" section, and update copy. Move image
- [ ] Replace "Begin taking contactless fare payments" section with "Get in touch" section

### PR DESCRIPTION
**Pull request by angela-tran**
Closes #467 

### Top section
- [x] Update "Explore this site to find support..." copy
- [x] Remove copy "Contracts update!"
- [x] Remove copy "U.S. public transit providers, we have news for you..."
- [x] Add View Contracts button in new style

### Lower sections
- [x] Remove map section
- [x] Remove "Modernize your fare collection system" section
- [x] Implement design for "What is Cal-ITP" section
- [x] Implement design for "Get in touch" section

### CODE REVIEW

**Comment by angela-tran** [comment]
I finished implementing the items that are in scope for #467.

Something that needs clarification: the spacing on the current site and the spacing shown in Figma do not match. Is this an intentional design update that we should be implementing as a part of this homepage effort?

The current spacing is using some odd values, and I don't know where these came from; they must've been based on something though, right? They were [added just a few months ago](https://github.com/cal-itp/mobility-marketplace/commit/31a0f5c9bcffcd9396e2847c93e57c6a8f368208#diff-95fd9cc2014803c6e8856d70211be6211ffc92c1ea604f49cd265e8b17b811aeR39).

image

image

image


image


The spacing in Figma looks to me like it's based off the 8-pt system, so it seems more aligned with how we've said we want to do spacing. 

image

image

This change should be its own ticket if it's confirmed that we're supposed to be implementing this.

**Comment by angela-tran** [comment]
I finished implementing the items that are in scope for #467.

Something that needs clarification @segacy1 @thekaveman: the spacing on the current site and the spacing shown in Figma do not match. Is this an intentional design update that we should be implementing as a part of this homepage effort?

The current spacing is using some odd values, and I don't know where these came from; they must've been based on something though, right? They were [added just a few months ago](https://github.com/cal-itp/mobility-marketplace/commit/31a0f5c9bcffcd9396e2847c93e57c6a8f368208#diff-95fd9cc2014803c6e8856d70211be6211ffc92c1ea604f49cd265e8b17b811aeR39).

image

image

image


image


The spacing in Figma looks to me like it's based off the 8-pt system, so it seems more aligned with how we've said we want to do spacing. 

image

image

This change should be its own ticket if it's confirmed that we're supposed to be implementing this.

**Comment by segacy1** [comment]
Hi @angela-tran! Yes, this does follow the 8-pt grid. Whenever I create new designs for mobimart or calitp.org, I automatically update with that design framework. I know we never discussed that explicitly for this ticket though—I'll do a better job noting that when we're scoping dev work in the future. If we can create a new ticket for this in the backlog that would be great

Also, I think you might be looking at my design sandbox. The design for implementation is [here](https://www.figma.com/file/TfWk1iDHdlt7bSA3DjQuQv/Mobility-Marketplace?type=design&node-id=7052-1740&mode=design).

**Comment by angela-tran** [comment]
Thank you @segacy1 — that is all very very helpful context

Re:

> If we can create a new ticket for updating the spacing in backlog that would be great

This sounds good to me

> Also, I think you might be looking at my design sandbox. The design for implementation is [here](https://www.figma.com/file/TfWk1iDHdlt7bSA3DjQuQv/Mobility-Marketplace?type=design&node-id=7052-1740&mode=design).

Oh yes, you're right that I was looking at a page under "DESIGN_____". I was looking there because it's linked from the description for https://github.com/cal-itp/mobility-marketplace/issues/463#issue-1872313323. Thanks for pointing this out. I can reference the one you linked

**Comment by angela-tran** [comment]
In Figma, I see that the content for the lower sections ("What is Cal-ITP?" and "Get in touch") are more or less vertically 
centered. 

image

The current CSS that we use to lay out these sections are `imaged-sections` and don't result in vertical centered-ness.

image


I have ideas on how to do it with Bootstrap's grid, which is really using CSS Flexbox, but the `imaged-section--X` classes are using CSS grid, so I'm not sure how to tweak this. @machikoyasuda or @vlad do you have ideas?

**Comment by angela-tran** [comment]
Or another thought: is the current spacing good enough for now until we take #490?

**Comment by thekaveman** [comment]
> Or another thought: is the current spacing good enough for now until we take #490?

Yeah I'm OK to wait to handle spacing all at once.

**Comment by angela-tran** [comment]
> Though I wonder how hard it would be in this PR to align the hero image with the two section images (or make the hero image slightly smaller to match)? They are just a bit off:

This was a good catch, and the change for it was pretty straightforward: https://github.com/cal-itp/mobility-marketplace/pull/489/commits/b6f16770c89994c15afa084bf7e313c178983ace

That style rule was from a much older version of the design (https://github.com/cal-itp/mobility-marketplace/pull/275), so I think it's fine to just remove it

**Comment by thekaveman** [comment]
Hmm @angela-tran I think we may have gone slightly the other way now? The two section images are larger (square) than the hero one now (same width, smaller height):

image

image

**Comment by machikoyasuda** [comment]
@angela-tran Haven't had a chance to really dig into this but:

- On Figma, all 3 images are the same height/width of 424 x 366
image

- BUT(!) the images are cropped _WITH_ white-space, so that the image width matches the grid columns of 4 columns. 

So one way to approach the image width/column horizontal spacing issue is to re-export the images _with_ the white space, make sure the images are the same dimensions and stick it in the somewhat overeengineered CSS Grid situation that Mobi Mart already has.

**Comment by angela-tran** [comment]
@machikoyasuda I came to the same conclusion and re-exported the images from Figma. Glad we were thinking the same

**Comment by machikoyasuda** [comment]
Small thing, could be done in a future ticket - but it is just a one-line deletion:

image

These `a`s now have an underline created by a border-bottom, making them extra thick and also further down lower.

But Figma has nice normal regular underlines now.




Which can be done by removing that border-bottom declaration:
image

It's extra-jarring because the super-thick border is touching the text from the line below, and getting really tight/messy to read.

**Comment by thekaveman** [comment]
@mrose914 can you please verify copy changes on the homepage: https://deploy-preview-489--cal-itp-mobility-marketplace.netlify.app/

**Review by thekaveman — APPROVED** [review]
Code and visuals LGTM

**Comment by angela-tran** [comment]
Sorry, I just noticed there are some things in the mobile view that need to be fixed.

- Sizing of hero title
- Centering titles for lower sections

| Current preview site | Figma |
| --- | --- |
| image | image |

**Comment by angela-tran** [comment]
> Small thing, could be done in a future ticket - but it is just a one-line deletion:
> ...
> These `a`s now have an underline created by a border-bottom, making them extra thick and also further down lower.
> 
> But Figma has nice normal regular underlines now.
> 
> Which can be done by removing that border-bottom declaration: 
> ...
> It's extra-jarring because the super-thick border is touching the text from the line below, and getting really tight/messy to read.

@machikoyasuda I went ahead and made this change in a1441caebb50b82f45c87633095e1886be84bf15

**Review by thekaveman — CHANGES_REQUESTED** [review]
Nice catch on the mobile titles. Looks like we need one more small change on mobile for centering the images:

image

image

In the browser devtools I changed the following and it worked:

```css
.imaged-section__image {
  justify-content: space-around;
}
```

This also looks OK on the normal view so maybe we just add this style in?

**Comment by angela-tran** [comment]
> This also looks OK on the normal view so maybe we just add this style in?

@thekaveman Sounds good to me, thanks!

**Review by thekaveman — APPROVED** [review]
Nice work!

**Pull request merged**
